/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NovaTreeNode {}
  interface NovaTreeSelect {}
}

declare global {


  interface HTMLNovaTreeNodeElement extends Components.NovaTreeNode, HTMLStencilElement {}
  var HTMLNovaTreeNodeElement: {
    prototype: HTMLNovaTreeNodeElement;
    new (): HTMLNovaTreeNodeElement;
  };

  interface HTMLNovaTreeSelectElement extends Components.NovaTreeSelect, HTMLStencilElement {}
  var HTMLNovaTreeSelectElement: {
    prototype: HTMLNovaTreeSelectElement;
    new (): HTMLNovaTreeSelectElement;
  };
  interface HTMLElementTagNameMap {
    'nova-tree-node': HTMLNovaTreeNodeElement;
    'nova-tree-select': HTMLNovaTreeSelectElement;
  }
}

declare namespace LocalJSX {
  interface NovaTreeNode extends JSXBase.HTMLAttributes<HTMLNovaTreeNodeElement> {}
  interface NovaTreeSelect extends JSXBase.HTMLAttributes<HTMLNovaTreeSelectElement> {}

  interface IntrinsicElements {
    'nova-tree-node': NovaTreeNode;
    'nova-tree-select': NovaTreeSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


