/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NovaTransfer {
    'disabled': boolean;
    'onChangeHandler': Function;
    'showSearch': boolean;
    'showSelectAll': boolean;
    'titles': string[];
  }
}

declare global {


  interface HTMLNovaTransferElement extends Components.NovaTransfer, HTMLStencilElement {}
  var HTMLNovaTransferElement: {
    prototype: HTMLNovaTransferElement;
    new (): HTMLNovaTransferElement;
  };
  interface HTMLElementTagNameMap {
    'nova-transfer': HTMLNovaTransferElement;
  }
}

declare namespace LocalJSX {
  interface NovaTransfer extends JSXBase.HTMLAttributes<HTMLNovaTransferElement> {
    'disabled'?: boolean;
    'onChangeHandler'?: Function;
    'showSearch'?: boolean;
    'showSelectAll'?: boolean;
    'titles'?: string[];
  }

  interface IntrinsicElements {
    'nova-transfer': NovaTransfer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


