import { EventEmitter } from "../../../dist/types/stencil.core";
export declare class NovaTransfer {
    data?: any;
    configuration?: any;
    styling?: any;
    columnStyle: any;
    operationStyle: any;
    wrapperStyle: any;
    renderItem: Function;
    filterOption: Function;
    showSearch: boolean;
    disabled: boolean;
    showSelectAll: boolean;
    search: EventEmitter;
    transferColumn: EventEmitter;
    scrollColumn: EventEmitter;
    select: EventEmitter;
    filter: EventEmitter;
    filteredItems: any[];
    selected: string[];
    transfered: string[];
    sourceFooter: boolean;
    targetFooter: boolean;
    el: HTMLElement;
    componentWillLoad(): void;
    componentDidLoad(): void;
    handleSelect(key: string): Promise<void>;
    private _handleSelect;
    private _handleSelectAll;
    private _handleSourceQuery;
    private _handleTargetQuery;
    private _getItems;
    private _handleItemsScroll;
    private _getTotalEnabledFromSource;
    private _getTotalEnabledFromTarget;
    render(): any;
    private _isThereSourceFooter;
    private _isThereTargetFooter;
    private _init;
    private _getSourceSelected;
    private _getTargetSelected;
    private _moveToTarget;
    private _moveToSource;
    private _isItemInTarget;
    private _emitSelectEvent;
    private _sourceIsEmpty;
    private _targetIsEmpty;
}
