/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NovaRate {
    'allowClear': boolean;
    'allowHalf': boolean;
    'character': string;
    'count': number;
    'defaultValue': number;
    'disabled': boolean;
  }
}

declare global {


  interface HTMLNovaRateElement extends Components.NovaRate, HTMLStencilElement {}
  var HTMLNovaRateElement: {
    prototype: HTMLNovaRateElement;
    new (): HTMLNovaRateElement;
  };
  interface HTMLElementTagNameMap {
    'nova-rate': HTMLNovaRateElement;
  }
}

declare namespace LocalJSX {
  interface NovaRate extends JSXBase.HTMLAttributes<HTMLNovaRateElement> {
    'allowClear'?: boolean;
    'allowHalf'?: boolean;
    'character'?: string;
    'count'?: number;
    'defaultValue'?: number;
    'disabled'?: boolean;
    'onOnRatingUpdated'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'nova-rate': NovaRate;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


